import {Alert, Nav, Providers, AuthAdmin} from "@/components";
import "./globals.css";
import {Inter} from "next/font/google";
import {getCurrentAdmin} from "./_actions/admins";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "TOL Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentAdmin = await getCurrentAdmin();

  return (
    <html data-theme="primary" lang="en">
      <body className={inter.className}>
        <Providers>
          <Alert />
          {!currentAdmin ? (
            <AuthAdmin />
          ) : (
            <>
              <div className="flex flex-col text-black lg:flex-row bg-black-1">
                <Nav />
                <div className="flex-1 bg-black-1 p-6 min-h-screen text-[#C2D0EA] overflow-x-auto">
                  {children}
                </div>
              </div>
            </>
          )}
        </Providers>
      </body>
    </html>
  );
}
